export const knowledgeBase: Map<string, string> = new Map([
    ['ai', "Artificial Intelligence, or AI, is the result of our efforts to automate tasks normally performed by humans, such as image pattern recognition, document classification, or a computerized chess rival. Artificial Intelligence - Machine Learning - Deep Learning - Symbolic AI  (Fig. 1) AI encompasses various approaches: Symbolic AI, also referred to as good old-fashioned AI (GOFAI), uses explicitly defined rules and symbolic representations for problem-solving. It's similar to traditional programming in the sense that predefined guidelines drive the process, however it's more advanced as it permits inference and adaptation to new situations. Machine Learning (ML) is another AI approach that allows algorithms to learn from data. Deep Learning (DL) is a subset of ML that uses multi-layered, artificial neural networks."],
    ['artificial intelligence', "Artificial Intelligence, or AI, is the result of our efforts to automate tasks normally performed by humans, such as image pattern recognition, document classification, or a computerized chess rival. Artificial Intelligence - Machine Learning - Deep Learning - Symbolic AI  (Fig. 1) AI encompasses various approaches: Symbolic AI, also referred to as good old-fashioned AI (GOFAI), uses explicitly defined rules and symbolic representations for problem-solving. It's similar to traditional programming in the sense that predefined guidelines drive the process, however it's more advanced as it permits inference and adaptation to new situations. Machine Learning (ML) is another AI approach that allows algorithms to learn from data. Deep Learning (DL) is a subset of ML that uses multi-layered, artificial neural networks."],
    ['machine learning', "Machine Learning, or ML, focuses on the creation of systems or models that can learn from data and improve their performance in specific tasks, without the need to be explicitly programmed, making them learn from past experiences or examples to make decisions on new data. This differs from traditional programming, where human programmers write rules in code, transforming the input data into desired results Now, I am going to explain the most relevant terms in ML: Model: A model is the representation that explains the observations. The trained model is the result of applying an ML algorithm with a data set. This trained model, now primed with specific patterns and understandings from the dataset, is subsequently used to draw inferences from new observations.  Algorithm: An algorithm is a procedure implemented in code that guides a model in learning from data it's given. There are many machine learning algorithms.  Training: Training is the iterative process of applying the learning algorithm. Consists in: * Applying the model (as is) to the variables of the observations and obtain the results according to the model. * Comparing the model results with the actual values. * Establishing a way to calculate the error between the model and reality. * Using the error as a basis to update the model in order to reduce the error. * Repeating until the model reaches the error levels that we have proposed and is capable of generalizing with observations that it has not seen in training."],
    ['deep learning', 'Deep learning is a subset of ML using neural networks with multiple layers.'],
    ['natural language processing', 'NLP is a branch of AI that helps computers understand and interpret human language.'],
    ['computer vision', 'Computer vision is an AI field that trains computers to interpret and understand visual information.'],
    ['robotics', 'Robotics is a field that combines computer science and engineering to design and build robots.'],
    ['blockchain', 'Blockchain is a decentralized, distributed ledger technology.'],
    ['cryptocurrency', 'Cryptocurrency is a digital or virtual currency that uses cryptography for security.'],
    ['internet of things', 'IoT refers to the interconnected network of physical devices embedded with electronics, software, and sensors.'],
    ['gmtstudio', 'GMTStudio is a platform that offers various services, including an AI WorkSpace and a social media platform called Theta.'],
    ['theta', 'Theta is a social media platform developed by GMTStudio, offering unique features for connecting and sharing content.'],
    ['ai workspace', 'The AI WorkSpace is a powerful tool offered by GMTStudio for AI development, allowing users to train models and run experiments.'],
    ['machine learning applications', 'Machine learning has various applications, including image recognition, natural language processing, and predictive analytics.'],
    ['blockchain technology', 'Blockchain technology has applications beyond cryptocurrency, including supply chain management and secure voting systems.'],
    ['internet of things applications', 'IoT applications include smart home devices, industrial automation, and connected healthcare systems.'],
    ['sustainable development', 'Sustainable development is an approach to economic growth that protects the environment and ensures social equity for present and future generations.'],
    ['global health', 'Global health focuses on improving health and achieving health equity for all people worldwide, addressing both medical and social determinants of health.'],
    ['cultural anthropology', 'Cultural anthropology is the study of human cultures, their beliefs, practices, values, ideas, technologies, economies and other domains of social and cognitive organization.'],
    ['behavioral economics', 'Behavioral economics combines insights from psychology, judgment, decision making, and economics to generate a more accurate understanding of human behavior.'],
    ['urban planning', 'Urban planning is a technical and political process concerned with the development and design of land use and the built environment in urban areas.'],
    ['comparative literature', 'Comparative literature is an academic field dealing with the study of literature and cultural expression across linguistic, national, and disciplinary boundaries.'],
    ['marine biology', 'Marine biology is the scientific study of organisms in the ocean or other marine bodies of water, including their behaviors and interactions with the environment.'],
    ['geopolitics', "Geopolitics is the study of the effects of Earth's geography on politics and international relations, particularly with respect to foreign policy of different states."],
    ['art history', 'Art history is the study of objects of art in their historical development and stylistic contexts, including genre, design, format, and style.'],
    ['philosophy of science', 'Philosophy of science is a branch of philosophy concerned with the foundations, methods, and implications of science, including the natural sciences and social sciences.'],
    ['linguistics', 'Linguistics is the scientific study of language, including its structure, evolution, and relationship to human behavior and the human brain.'],
    ['public health', 'Public health is the science of protecting and improving the health of people and their communities through education, policy making and research for disease and injury prevention.'],
    ['international relations', 'International relations is the study of the interactions among various actors in the international system, including states, international organizations, NGOs, and multinational corporations.'],
    ["world history", "World history encompasses the study of human societies and their development across time and space, from ancient civilizations to modern globalization."],
    ["economics", "Economics is the social science that studies the production, distribution, and consumption of goods and services."],
    ["psychology", "Psychology is the scientific study of the mind and behavior, exploring how people think, feel, and act."],
    ["sociology", "Sociology is the study of human society, social relationships, and institutions, examining how they shape and are shaped by individuals."],
    ["political science", "Political science focuses on systems of government, political behavior, and the analysis of political issues and policies."],
    ["environmental science", "Environmental science is an interdisciplinary field that integrates physical, biological, and information sciences to study and address environmental issues."],
    ["astronomy", "Astronomy is the study of celestial objects, space, and the physical universe as a whole."],
    ["geology", "Geology is the science that deals with the Earth's physical structure and substance, its history, and the processes that act on it."],
    ["oceanography", "Oceanography is the study of the physical and biological aspects of the ocean."],
    ["meteorology", "Meteorology is the scientific study of the atmosphere and weather patterns."],
    ["nutrition", "Nutrition is the study of nutrients in food, how the body uses them, and the relationship between diet, health, and disease."],
    ["archaeology", "Archaeology is the study of human history and prehistory through the excavation and analysis of artifacts and physical remains."],
    ["music theory", "Music theory is the study of the fundamental elements of music including rhythm, harmony, and form."],
    ["film studies", "Film studies involves the critical analysis of cinema, including its history, theory, and social impact."],
    ["fashion design", "Fashion design is the art of applying design, aesthetics, and natural beauty to clothing and accessories."],
    ["architecture", "Architecture is the art and science of designing and constructing buildings and other physical structures."],
    ["game theory", "Game theory is the study of strategic decision-making in competitive scenarios."],
    ["criminology", "Criminology is the scientific study of crime, including its causes, consequences, and control."],
    ["epistemology", "Epistemology is the branch of philosophy concerned with the theory of knowledge."],
    ["ethics", "Ethics is the branch of philosophy that involves systematizing, defending, and recommending concepts of right and wrong behavior."],
    ["philosophy", "Philosophy is the study of the fundamental nature of reality, existence, knowledge, logic, and ethics."],
    ["psychology", "Psychology is the scientific study of the mind and behavior, exploring how people think, feel, and act."],
    ["sociology", "Sociology is the study of human society, social relationships, and institutions, examining how they shape and are shaped by individuals."],
    ["political science", "Political science focuses on systems of government, political behavior, and the analysis of political issues and policies."],
    ["environmental science", "Environmental science is an interdisciplinary field that integrates physical, biological, and information sciences to study and address environmental issues."],
    ["astronomy", "Astronomy is the study of celestial objects, space, and the physical universe as a whole."],
    ["economics", "Economics is the social science that studies the production, distribution, and consumption of goods and services."],
    ["statistics", "Statistics is the study of the collection, analysis, interpretation, presentation, and organization of data."],
    ['neural networks', 'Neural networks are a series of algorithms that attempt to recognize underlying relationships in a set of data through a process that mimics the way the human brain operates.'],
    ['reinforcement learning', 'Reinforcement learning is an area of machine learning concerned with how agents ought to take actions in an environment to maximize some notion of cumulative reward.'],

]);
